- src/components/NavBar.js
- src/hooks/useAuth.js
This was supposed to be in the #41 PR but somehow didn't get pushed
> refactor: use a hook for auth

- package-lock.json
- package.json
- src/app/opportunities/page.js
- src/app/profile/page.js
- src/app/signup/page.js
- src/components/Container.jsx
- src/components/FilterTag.jsx
- src/components/Input.jsx
- src/components/OpportunityCard.jsx
- src/components/ProfileHero.jsx
- src/components/ProfileTabs.jsx
- src/components/Search.jsx
- src/components/Section.jsx
- src/components/Tabs.jsx
- src/components/Tag.jsx
Created a bunch of components and added them to their retrospective pages
Closes #37 
Closes #36 
Closes #32
> feat: components

- src/app/opportunities/page.js
- src/components/Input.jsx
- src/components/ProfileHero.jsx
- src/components/Search.jsx
- src/components/Tabs.jsx
> tweak: modify search and input component

- src/api/fileApi.js
- src/app/conversations/page.js
- src/app/editprofile/page.js
- src/app/layout.js
- src/app/login/page.js
- src/app/profile/page.js
- src/app/signup/page.js
- src/components/Chat.jsx
- src/components/ConversationPreview.jsx
- src/components/Input.jsx
- src/components/MainNav.jsx
- src/components/ProfileHero.jsx
- src/contexts/AuthContext/UserProfileContext.js
- src/firebase/firebase.js
- src/hooks/useAuth.js
**What does this PR do?**
- Fix signup pages for both brand and creator
- Set user roles
- Add update feature
- Add toast messages
- fix error handling
**How should this be manually tested?**
1. Clone this repository and switch to `ft-backend-integration`
2. Install all required dependencies `npm install`
3. npm run dev
> Redefining schema

- src/components/Client/ClientDashboard.jsx
Fixes the styling of the opportunity panels
> fix: opportunity panels styling

- src/app/(auth)/signup/page.js
> fix: build error

- src/components/Client/ClientDashboard.jsx
- src/components/Form.jsx
- src/components/Input.jsx
- src/data/opportunity_data.json
- src/styles/globals.css
> feat: opportunity form

- src/app/(dashboard)/(creator)/opportunities/page.js
- src/app/(dashboard)/conversations/page.js
- src/app/layout.js
- src/components/Chat.jsx
- src/components/ConversationPreview.jsx
- src/helpers/dateFormatter.js
- src/redux/store/index.js
- Develop chat Functionalities 
- Configuring Redux
> Chat Message Functionalities and Configuring Redux

- .prettierrc.json
- src/app/(auth)/login/page.js
- src/app/(auth)/signup/page.js
- src/app/(auth)/template.js
- src/app/(dashboard)/conversations/page.js
- src/components/Button.jsx
- src/components/Chat.jsx
- src/components/Client/ClientDashboard.jsx
- src/components/ConversationPreview.jsx
- src/components/FilterTag.jsx
- src/components/Heading.jsx
- src/components/Input.jsx
- src/components/MainNav.jsx
- src/components/Panel.jsx
- src/components/ProfileIcon.jsx
- src/components/Tabs.jsx
Updates fields to match schema update
> tweak: sign up

- src/components/Client/EditOpportunityForm.jsx
> fix: default checked input

- src/app/(dashboard)/(creator)/opportunities/page.js
- src/app/(dashboard)/loading.js
- src/components/Creator/OpportunitiesSearch.jsx
- src/components/Modal.jsx
- src/components/Search.jsx
- Users can use the search input to filter opportunities
- A no opportunities found message is shown when there are no opportunities
> feat: opportunities search

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/components/Client/ClientOpportunityCard.jsx
- src/components/Client/EditOpportunityForm.jsx
- src/components/Client/OpportunityForm.jsx
- src/components/Creator/ProposalForm.jsx
- src/components/Form.jsx
- src/components/OpportunityCard.jsx
- src/data/opportunity_data.json
Refactored forms and added some error ui on unsuccessful submissions
> feat: form error UI and refactoring

- src/app/(auth)/loading.js
- src/app/(dashboard)/(client)/applications/[id]/page.js
- src/app/(dashboard)/(client)/applications/page.js
- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/components/Button.jsx
- src/components/Client/ApplicationCard.jsx
- src/components/Client/ClientDashboard.jsx
- src/components/Client/ClientOpportunityCard.jsx
- src/components/Client/EditOpportunityForm.jsx
- src/components/Client/OpportunityForm.jsx
- src/components/Creator/ProposalForm.jsx
- src/components/Modal.jsx
- src/components/ProfileHero.jsx
> feat: applications page

- src/app/(auth)/login/page.js
- src/app/redux/features/profile/authSlice.js
- src/app/redux/store.js
- src/components/MainNav.jsx
- Create a login slice
- Create a update logout functionalities
> Feature(Update Redux on login state)

- src/app/(dashboard)/profile/page.js
- src/app/redux/features/profile/profileSlice.js
- src/components/EditProfileForm.jsx
- src/components/EditProfileModal.jsx
- Open the form model and close it automatically once the user is updated 
- Add a loading text
- Update any user profile data
> Fix(Update User profile)

- src/helpers/getServerComponentData.js
> tweak: do not show archived opp on user profiles

- src/app/(dashboard)/settings/edit-profile/page.js
- src/components/AuthInput.jsx
- src/components/Brand/CreateOpportunityForm.jsx
- src/components/Brand/EditOpportunityForm.jsx
- src/components/Creator/ProposalForm.jsx
- src/components/Form.jsx
- src/components/SignUpForm.jsx
- src/hooks/useAuth.js
- src/styles/globals.css
Display error message and don't redirect to verify if sign up isn't successful
> feat: add error messages for sign up

- src/components/SignUpForm.jsx
- src/hooks/useAuth.js
> Fix signup issue

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/app/(dashboard)/settings/page.js
- src/components/AuthInput.jsx
- src/components/ForgotPasswordForm.jsx
- src/components/Form.jsx
- src/components/LoginForm.jsx
- src/components/SignUpForm/SignUpForm.jsx
- src/context/UserContext.jsx
- src/data/signup_data.json
- Created an Error and Success component to make sure the same component is used across the application to handle form success and error messages
- Refactored step form click handler to only check the fields for the fields of the current step only
- Added more error messages
> tweak: form

- src/app/(dashboard)/profile/[id]/page.js
- src/app/(dashboard)/settings/edit-profile/page.js
- src/components/Brand/ApplicationsModal.jsx
- src/components/Brand/BrandProfileOpportunities.jsx
- src/components/Brand/CreateOpportunityForm.jsx
- src/components/Creator/CreatorProfileTabs/CreatorProfileTabs.jsx
- src/components/Creator/CreatorProfileTabs/Credits.jsx
- src/components/Creator/CreatorProfileTabs/PlayerEmbed.jsx
- src/components/Creator/CreatorProfileTabs/Reviews.jsx
- src/components/Creator/CreatorProfileTabs/Showcase.jsx
- src/components/Creator/CreditsInput.jsx
- src/components/Creator/ShowcaseInput.jsx
- src/components/Creator/ShowreelInput.jsx
- src/components/Profile.jsx
- src/components/ProfileHero.jsx
- src/helpers/getServerComponentData.js
- Refactors Profile to use the same component, with conditional renders in the children to handle exceptions
- Prepared ProfileTabs to consume update to the backend for user profiles with the addition of a profile_meta field
- Created a PlayerEmbed components to use to render the different embeds. Doesn't look great so not sure if this will be kept
- Removed unneseccary console logs
- Added more client validation for profile meta inputs
> feat: profile meta

- src/app/layout.js
- src/components/Heading.jsx
- tailwind.config.js
Adds Anton using next/font, closes #195
> feat: anton

- src/app/(dashboard)/settings/password/page.js
- src/components/AuthInputController.jsx
- src/components/LoginForm.jsx
- src/components/SignUpForm/SignUpFormStep.jsx
Users can review their password. So we don't have to use a confirm password field and reduce clutter
> Add an eye icon to the password fields

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
Update single opportunities to match changes to be
> fix: opportunities

- src/app/(dashboard)/settings/page.js
Change route name on update email
> Change route name

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/app/(dashboard)/conversations/page.js
- src/components/Brand/BrandApplicationCard.jsx
- src/components/Brand/BrandOpportunities.jsx
- src/components/Brand/CreateOpportunityForm.jsx
- src/components/ChatList.jsx
- src/components/Creator/ApplicationProposalForm.jsx
- src/components/SignUpForm/SignUpForm.jsx
- src/components/SingleChat.jsx
- src/helpers/getServerComponentData.js
- src/hooks/useOpportunities.js
- Chat is automatically selected if provided in search params like this `/conversations?room=${room_id}`
- Fixes opportunity rendering
> tweak: chat

- src/components/Brand/ApplicationsModal.jsx
- src/components/Brand/BrandOpportunities.jsx
- src/components/SingleChat.jsx
- Can filter opportunities by their status
- Updates arrows to use arrows from design
> fix: swiper filter and rendering

- src/components/Form.jsx
- src/data/opportunity_form_data.json
> tweak: checkbox

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/components/Brand/BrandApplicationCard.jsx
- src/components/OpportunityCard.jsx
- src/helpers/getServerComponentData.js
> fix: display correct data on opportunity cards

- src/app/(dashboard)/settings/edit-profile/page.js
- src/components/Creator/CreatorProfileTabs/Showcase.jsx
- src/components/Creator/CreditsInput.jsx
- Adds a play button to toggle episode preview audio
Closes #259
> feat: spotify preview audio

- src/app/(dashboard)/profile/[id]/page.js
- src/app/(dashboard)/settings/edit-profile/page.js
- src/app/(dashboard)/settings/page.js
- src/app/(dashboard)/settings/password/page.js
- src/app/(dashboard)/settings/template.js
- src/app/(dashboard)/thankyou/page.js
- src/components/Admin/CreateUserForm.jsx
- src/components/AuthInputController.jsx
- src/components/Brand/BrandOpportunities.jsx
- src/components/Brand/BrandOpportunityCard.jsx
- src/components/Brand/CreateOpportunityForm.jsx
- src/components/Button.jsx
- src/components/Creator/CreditsInput.jsx
- src/components/Creator/ShowcaseInput.jsx
- src/components/Creator/ShowreelInput.jsx
- src/components/Form.jsx
- src/components/InfoCard.jsx
- src/components/ProfileHero.jsx
- src/components/Subscribe.jsx
- src/data/opportunity_form_data.json
- Refactor - updated localUser and setLocalUser to formData / setFormData to improve code readability 
- Fixed bug where email address wouldn't render on refresh
- Made password toggle a button 
- Added a handler to the ProfileHero for company names, so that they will display instead of the users name if there is one
- Updated ui of button and infocard
- Fix create opportunity form
> tweak: various

- src/app/(auth)/template.js
- src/components/Brand/BrandApplicationCard.jsx
- src/components/Brand/BrandOpportunities.jsx
- src/components/Brand/BrandProfileOpportunities.jsx
- src/components/Creator/CreatorApplicationCard.jsx
- src/components/Creator/CreatorDashboard.jsx
- src/components/Creator/CreatorProfileTabs/Showcase.jsx
- src/components/MainNav.jsx
- src/components/OpportunityCard.jsx
- src/components/ProfileHero.jsx
- src/components/ProfileIcon.jsx
- src/components/StatsPanel.jsx
- src/components/Tag.jsx
Resolves https://github.com/content-is-queen/creator-platform/issues/90, resolves https://github.com/content-is-queen/creator-platform/issues/139
- Makes application responsive on mobile, tablet and desktop
- Improves swiper ux, hides arrow if there are no projects to swipe to and snaps to size of viewport
> feat: responsiveness, bug: swiper fix

- src/components/Admin/AdminOpportunitiesTableRow.jsx
- src/components/Admin/AdminUserTableRow.jsx
- src/components/Brand/BrandOpportunityCard.jsx
- src/components/MainNav.jsx
> Replace all instances of the SubMenu component to use headless ui's menu  #216

- src/app/(dashboard)/(creator)/opportunities/[id]/page.js
- src/components/ChatList.jsx
- src/components/SingleChat.jsx
Adds conversation participant name to converastion chat list and single chat and the opportunity title
> feat: add conversation data

- src/components/ResetPasswordForm.jsx
> pr- reset-password toggle should reveal password #281

- src/components/Brand/ApplicationsModal.jsx
- src/components/Brand/BrandApplicationCard.jsx
- src/components/ChatList.jsx
- src/components/Creator/ApplicationProposalForm.jsx
- src/data/opportunity_form_data.json
-Fix application popup issue
-Fetch the user profile with referencing the image -Fix variable missmatch issues
-Fix proposal issue due to missmatch in variables
[Done]
> Use reference to display user profile photo every where:

- src/components/Creator/ApplicationProposalForm.jsx
Improve the display message in case a user tries to apply twice
> Prevent user to apply twice

- src/api/api.js
- src/components/Creator/ApplicationProposalForm.jsx
- src/components/Creator/OpportunitiesSearch.jsx
- Request interceptor checks localStorage for existing token and adds it to request headers
- Response interceptor catches 401 (Unauthorized) errors and attempts token refresh
- On successful token refresh, the original failed request is retried automatically
- Failed refresh attempts trigger a logout flow and redirect to login page
- Added SSR safety checks with `typeof window !== 'undefined'`
> Fix 404 error by adding interceptors
